### PR TITLE
include facebook entreprise domain

### PR DESCRIPTION
**Pull request by setop**
add domain "workplace.com" to matches.

### CODE REVIEW

**Comment by setop** [comment]
I tested it locally, it works !
So happy to have found this add-ons. This hidden redirection thing was %ù$ù* me for so long.
I wait for an official release including this patch to share it with my colleagues.
Thanks for your work @Mte90

**Comment by setop** [comment]
does not seems to work after all :(

**Comment by Mte90** [comment]
Hi setop, I don't have facebook workplace to test.
I don't know how much change, in your case the extension work also with the normal facebook?
I am trying to investigate #14 and #15 but I cannot replicate so I need more info.

**Comment by setop** [comment]
> Hi setop, I don't have facebook workplace to test.
> I don't know how much change, in your case the extension work also with the normal facebook?

Hi, I don't have public facebook, only the professional version my compagny compel me to use.

> I am trying to investigate #14 and #15 but I cannot replicate so I need more info.

Yeh, the HTML structure they use is all about obfuscation : multiple layers of "a" tags and others just to make the user she/he will go directly to the pointed link whereas it goes though the tracking system of FB. Shame on them.

The workaround I found, which is weird, it that the middle click goes straight to the linked content where a left click or a "copy location" points to the redirected one. Until FB finds a way to capture that also :(

**Comment by Mte90** [comment]
Yes FB does horrible things with markup, as it is now the extension track all the anchors so should work but I need a html to see if maybe that version requires a different selector.

AS you can see the selector is https://github.com/Mte90/facebook-direct-links/blob/master/direct.js#L49

**Pull request closed without merging**
