### PR TITLE
Add some Facebook URL clean ups

### PR DESCRIPTION
**Pull request by PeterDaveHello**
cc #21

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
In case you need some reference, but I don't think I'll just copy and paste them all, just as reference:

- https://gitlab.com/anti-tracking/ClearURLs/rules/-/blob/master/data.json
- https://github.com/Smile4ever/Neat-URL/blob/master/data/default-params-by-category.json

**Comment by Mte90** [comment]
I will do a new release ASAP but I will wait if you have more PR to do.

**Comment by PeterDaveHello** [comment]
@Mte90 I'll like to add some rules `utm_` ;)

**Comment by Mte90** [comment]
ok I will wait for more Pr for a new release :-)

**Pull request merged**
